name: mtl_env
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib-base=3.4.3
  - pandas=1.3.3
  - pip=21.3
  - python=3.9.7
  - rdkit=2021.03.5
  - scikit-learn=1.0
  - scipy=1.7.1
  - pip:
    - jupyter==1.0.0
    - keras==2.6.0
    - keras-preprocessing==1.1.2
    - numpy==1.19.5
    - tensorboard==2.6.0
    - tensorflow==2.6.0
